defmodule ErrorDemo.Repo.Migrations.CreateTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:parents, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:grandpappy_id, :uuid)
    end

    create table(:grandpappies, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
    end

    alter table(:parents) do
      modify(
        :grandpappy_id,
        references(:grandpappies,
          column: :id,
          name: "parents_grandpappy_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create table(:children, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)

      add(
        :parent_id,
        references(:parents,
          column: :id,
          name: "children_parent_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:children, "children_parent_id_fkey"))

    drop(table(:children))

    drop(constraint(:parents, "parents_grandpappy_id_fkey"))

    alter table(:parents) do
      modify(:grandpappy_id, :uuid)
    end

    drop(table(:grandpappies))

    drop(table(:parents))
  end
end
