defmodule ErrorDemo.Repo.Migrations.RemoveToysFromParent do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:toys) do
      remove(:parent_id)
    end
  end

  def down do
    alter table(:toys) do
      add(
        :parent_id,
        references(:parents,
          column: :id,
          name: "toys_parent_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end
end
